# Generated by Django 4.2.20 on 2025-07-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0005_applicationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='early_consideration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='regular_consideration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
